name: Check MDX Links

on:
  pull_request:
    branches: [dev]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn global add tsx
      - name: Start Dev Server
        run: |
          yarn dev &
          sleep 15
      - name: Check links
        run: yarn check-links
      - name: Stop Dev Server
        run: kill $(jobs -p) || true # Ensures that the dev server process is killed
